### PR TITLE
Extending drivers subcommand to also show supported device IDs

### PR DESCRIPTION
**Pull request by Bhavna2020**
this fixes issue #157.

### CODE REVIEW

**Review by michaelrsweet — CHANGES_REQUESTED** [review]
OK, as the primary consumer of this data is going to be system-level tools for auto-adding printers, I think we need to make the output more software-friendly.

The current output has the driver name (no spaces allowed) followed by whitespace and then the description (anything allowed besides newlines). At the very least we should add quotes around the description and device ID strings, e.g.:

    driver_name "Driver Description" "MFG:Foo;MDL:Bar;CMD:PCL;..."

We could also use CSV or some other well-known format to make it easier to parse. Check with @tillkamppeter to see what his preferred format will be.

**Comment by tillkamppeter** [comment]
@michaelrsweet thanks for the hint, I gace a similar hint on issue #158 but not on issue #157.
The use of quotes for column 2 and 3 is OK here, a CSV would be not such a good idea as the device ID can contain commas.
@Bhavna2020, could you implement it this way? Thanks.

**Comment by Bhavna2020** [comment]
OK, I have made the changes.

**Comment by tillkamppeter** [comment]
@Bhavna2020, to check whether a Printer Application supports a printer specified by its device ID you **should not** parse ythe ID and go through the driver list by yourself but instead, let the Printer Application do exactly the same as it does when you add the printer with driver selection "auto". You need to call the auto-add callback function with the device ID of the printer as argument (`system->autoadd_cb`).

**Pull request closed without merging**
