### PR TITLE
WIP : PAPPL Scan API Integration

### PR DESCRIPTION
**Pull request by Kappuccino111**
Actively updating for solving #130, #131 , #133 , #134.

### CODE REVIEW

**Review by michaelrsweet — CHANGES_REQUESTED** [review]
This isn't a complete implementation.

**Comment by Kappuccino111** [comment]
@michaelrsweet, the implementation is still a work in progress. I have now pushed the scanner-accessors.c file. One doubt that I have is that `papplSystemAddEvent()` is pre-configured for printers, and hence passing a scanner object while using `papplScannerResume()` or `papplScannerPause()` creates warnings. Any ideas on how to proceed with this? For now, I am simply debugging to the terminal.

**Comment by michaelrsweet** [comment]
> @michaelrsweet, the implementation is still a work in progress. All updates are regularly posted on the comments in #130
> 
> I have now pushed the scanner-accessors.c file. One doubt that I have is that `papplSystemAddEvent()` is pre-configured for printers, and hence passing a scanner object while using `papplScannerResume()` or `papplScannerPause()` creates warnings. Any ideas on how to proceed with this? For now, I am simply debugging to the terminal.

For now I would add a different version of papplSystemAddEvent that accepts the scanner pointer. Longer term we'll need to do something more coherent, of course, but for now a separate function will do just fine for a first implementation.

**Comment by Kappuccino111** [comment]
@tillkamppeter https://github.com/michaelrsweet/pappl/pull/349/commits/40786982e029e9aeff4ecd7be182cc381b08503a updates the scanner-driver.c code.

**Comment by michaelrsweet** [comment]
Closing for now. This needs to be rebased to PAPPL master (2.0).

**Pull request closed without merging**
