### PR TITLE
Fix darkness calculation in web interface

### PR DESCRIPTION
**Pull request by proski**
Round stored percent values to the closest hardware darkness value.

### CODE REVIEW

**Review by michaelrsweet — COMMENTED** [review]
You can't just round the number in one place.

**Comment by proski** [comment]
The original code would only preserve 0%, 20%, 40%, 60%, 80% and 100% for TSPL driver with 16 darkness levels. Other values would slide one step towards 0% on every save.

**Comment by michaelrsweet** [comment]
OK, I've re-tested and agree.

**Comment by michaelrsweet** [comment]
[master 7a395b9] Round darkness value (Issue #333)

[v1.4.x 8f62251] Round darkness value (Issue #333)

**Pull request closed without merging**
